# Generated by Django 3.2.6 on 2021-08-24 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, unique=True, verbose_name='Категория')),
                ('category_slug', models.SlugField(max_length=100, verbose_name='Слаг категории')),
            ],
        ),
        migrations.CreateModel(
            name='CountryOfOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryoforigin_name', models.CharField(max_length=100, unique=True, verbose_name='Страна происхождения')),
                ('countryoforigin_slug', models.SlugField(max_length=100, verbose_name='Слаг страны происхождения')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50, unique=True, verbose_name='Единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True, verbose_name='Наименование товара')),
                ('product_slug', models.SlugField(max_length=200, verbose_name='Слаг товара')),
                ('product_description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Цена товара')),
                ('product_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество товара на складе')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%M/%D', verbose_name='Фото товара')),
                ('is_available', models.BooleanField(blank=True, default=True, null=True, verbose_name='Доступность')),
                ('product_categories', models.ManyToManyField(blank=True, null=True, to='main_app.Category', verbose_name='Категории')),
                ('product_countriesoforigin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.countryoforigin', verbose_name='Страны происхождения')),
                ('product_units', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.unitofmeasure', verbose_name='')),
            ],
        ),
    ]
